config/routes.rb
Rails.application.routes.draw do
  devise_for :restaurant_owners
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :users, only: [] do
    member do
      patch :restaurant_mode
      patch :experience_mode
    end
  end

  resources :bookings, only: [] do
    member do
      patch :accept
      patch :decline
    end
  end

  get "restaurant_search", to: "restaurants#search"

  resources :restaurants, only: [:index, :show, :new, :create, :edit, :update] do
    resources :bookings, only: [:new, :create]
  end

  get "experience_search", to: "experiences#search"

  resources :experiences, only: [:index, :show, :new, :create, :edit, :update] do
    resources :bookings, only: [:new, :create]
  end

  root "restaurants#index"

  get "/dashboard", to: "pages#dashboard"
  get "webmanifest"    => "pwa#manifest"
  get "service-worker" => "pwa#service_worker"
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :restaurant_owner
  has_many :bookings, dependent: :destroy
  has_many :dishes, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, presence: true

  has_one_attached :photo
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :search]

  def index
    @restaurants = Restaurant.all
  end

  def search
    restaurants = Restaurant.all

    if params[:food_preferences].present?
      restaurants = restaurants.where("food_preferences @> ARRAY[?]::varchar[]", params[:food_preferences])
    end

    if params[:food_restrictions].present?
      restaurants = restaurants.where("food_restrictions @> ARRAY[?]::varchar[]", params[:food_restrictions])
    end

    if params[:address].present? && params[:walking_distance].present?
      # Convert walking time to meters (assuming average walking speed of 5km/h)
      # 5km/h = 83.33m/min
      walking_minutes = params[:walking_distance].first.to_i
      distance_in_meters = walking_minutes * 83.33

      # Filter restaurants within walking distance using Geocoder
      restaurants = restaurants.near(params[:address], distance_in_meters / 1000.0, units: :km)
    end

    # Using RANDOM() with a seed based on current timestamp to ensure different results
    @restaurant = restaurants.order(Arel.sql("RANDOM() * extract(epoch from now())::integer")).first

    if @restaurant
      redirect_to restaurant_path(@restaurant, food_preferences: params[:food_preferences], food_restrictions: params[:food_restrictions], address: params[:address], walking_distance: params[:walking_distance])
    else
      redirect_to restaurants_path, notice: "No matching restaurants found"
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])

    query = Restaurant.all.where.not(id: @restaurant.id)

    if params[:food_preferences].present?
      query = query.where("food_preferences @> ARRAY[?]::varchar[]", params[:food_preferences])
    end

    if params[:food_restrictions].present?
      query = query.where("food_restrictions @> ARRAY[?]::varchar[]", params[:food_restrictions])
    end

    @other_restaurants = query.order(Arel.sql("RANDOM() * extract(epoch from now())::integer")).first(3)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant successfully added!"
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :location, :rating, :description)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<div data-controller="roulette">
  <%= form_with url: restaurant_search_path, method: :get, class: "flex flex-col items-center gap-2", data: { roulette_target: "form" } do %>

    <div class="flex flex-col min-h-screen">
      <div class="flex justify-between items-center p-4 bg-white shadow-sm">
        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path,  data: { turbo_method: :delete }, class: "z-10 bg-white rounded-full p-2" do %>
            <i class="fa-solid fa-right-from-bracket"></i>
          <% end %>
        <% end %>
        
        <div data-controller="modal" class="w-full">
          <div class="relative z-20 hidden" data-modal-target="dialog" aria-labelledby="modal-title" role="dialog" aria-modal="true">
            <div class="fixed inset-0 bg-black/80 transition-opacity" aria-hidden="true"></div>

            <div  class="fixed inset-0 z-10 w-screen overflow-y-auto">
              <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">

                <div class="relative transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">
                  <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                    <div class="sm:flex sm:items-start">

                      <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                        <div class="mt-2">

                          <%= tag.div data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]} do %>
                            <%= text_field_tag :address, nil, data: { address_autocomplete_target: "address" }, class: "w-full hidden" %>
                          <% end %>

                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="bg-gray-50 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
                    <button type="button" data-action="modal#close" class="inline-flex w-full justify-center rounded-md bg-black px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-gray-800 sm:ml-3 sm:w-auto">Apply</button>
                    <button type="button" data-action="modal#close" class="mt-3 inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 shadow-xs ring-gray-300 ring-inset hover:bg-gray-50 sm:mt-0 sm:w-auto">Cancel</button>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <button  type="button" data-action="modal#open" class="relative flex items-center w-4/5 rounded-full border-none outline-none mx-2 px-3 py-2 text-sm/7 font-medium bg-gray-100">
            <span class="mr-2">📍</span>
            <span id="location">My location</span>
          </button>
        </div>


        <div class="flex gap-1 rounded-full bg-[#6A6A6A]/10" role="tablist" aria-orientation="horizontal">
          <%= link_to restaurants_path, class: "isolate group flex items-center rounded-full px-4 py-2 text-sm/7 font-medium bg-black text-white" do %>
            <i class="fa-solid fa-utensils"></i>
          <% end %>
          <%= link_to experiences_path, class: "isolate group flex items-center rounded-full px-4 py-2 text-sm/7 font-medium text-black" do %>
            <i class="fa-solid fa-mountain-sun"></i>
          <% end %>
        </div>
      </div>

      <div class="flex flex-col gap-4 p-4">
        <div data-controller="modal" class="w-full">
          <div class="relative z-20 hidden" data-modal-target="dialog" aria-labelledby="modal-title" role="dialog" aria-modal="true">
            <div class="fixed inset-0 bg-black/80 transition-opacity" aria-hidden="true"></div>

            <div  class="fixed inset-0 z-10 w-screen overflow-y-auto">
              <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">

                <div class="relative transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">
                  <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                    <div class="sm:flex sm:items-start">

                      <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                        <div class="mt-2">
                          <p class="text-sm text-gray-500">Select your food preferences and dietary restrictions below.</p>

                          <div class="mt-4">
                            <h4 class="font-medium text-gray-700 mb-2">Preferred Food Style</h4>
                            <div class="flex flex-wrap gap-2">

                              <% FOOD_PREFERENCES.each do |preference| %>
                                <div class="preference-pill">
                                  <%= check_box_tag "food_preferences[]", preference, false, id: "preference_#{preference.parameterize}", class: "hidden" %>
                                  <label for="preference_<%= preference.parameterize %>" class="inline-block px-3 py-1 rounded-full bg-gray-200 text-sm cursor-pointer hover:bg-gray-300 transition-colors">
                                    <%= preference %>
                                  </label>
                                </div>
                              <% end %>
                            </div>
                          </div>

                          <div class="mt-4">
                            <h4 class="font-medium text-gray-700 mb-2">Dietary Restrictions</h4>
                            <div class="flex flex-wrap gap-2">

                              <% FOOD_RESTRICTIONS.each do |restriction| %>
                                <div class="restriction-pill">
                                  <%= check_box_tag "food_restrictions[]", restriction, false, id: "restriction_#{restriction.parameterize}", class: "hidden" %>
                                  <label for="restriction_<%= restriction.parameterize %>" class="inline-block px-3 py-1 rounded-full bg-gray-200 text-sm cursor-pointer hover:bg-gray-300 transition-colors">
                                    <%= restriction %>
                                  </label>
                                </div>
                              <% end %>
                            </div>
                          </div>

                          <div class="mt-4">
                            <h4 class="font-medium text-gray-700 mb-2">Walking distance</h4>
                            <div class="flex flex-wrap gap-2 justify-center">

                              <% ["5 min", "10 min",  "15 min"].each do |distance| %>
                                <div class="restriction-pill">
                                  <%= check_box_tag "walking_distance[]", distance, false, id: "walking_distance_#{distance.parameterize}", class: "hidden" %>
                                  <label for="walking_distance_<%= distance.parameterize %>" class="inline-block px-3 py-1 rounded-full bg-gray-200 text-sm cursor-pointer hover:bg-gray-300 transition-colors">
                                    <%= distance %>
                                  </label>
                                </div>
                              <% end %>
                            </div>
                          </div>

                          <style>
                            .preference-pill input:checked + label,
                            .restriction-pill input:checked + label {
                              background-color: #000;
                              color: #fff;
                            }
                          </style>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="bg-gray-50 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
                    <button type="button" data-action="modal#close" class="inline-flex w-full justify-center rounded-md bg-black px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-gray-800 sm:ml-3 sm:w-auto">Apply</button>
                    <button type="button" data-action="modal#close" class="mt-3 inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 shadow-xs ring-gray-300 ring-inset hover:bg-gray-50 sm:mt-0 sm:w-auto">Cancel</button>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <button type="button" data-action="modal#open" class="relative flex items-center w-full rounded-full border-none outline-none pl-4 pr-12 py-2 text-sm/7 font-medium bg-gray-100">
            Food Restrictions, Preferences

            <div class="absolute right-3">
              <i class="fa-solid fa-filter"></i>
            </div>
          </button>
        </div>
      </div>


      <div class="flex justify-center items-center z-10">
        <div class="relative h-[220px] w-[220px] transform translate-y-15 wheel-container ">
          <div class="arrow absolute -top-[10px] left-1/2 transform -translate-x-1/2 w-10 h-10 bg-green-600 z-10" style="clip-path: polygon(50% 100%, 0% 0%, 100% 0%);"></div>
          <canvas data-roulette-target="canvas" id="wheel" width="220" height="220" class="transition-transform duration-[5000ms] ease-[cubic-bezier(0.17,0.67,0.12,0.99)]"></canvas>
        </div>
      </div>


      <div class="mt-auto bg-lime-200 p-8 text-center" style="clip-path: ellipse(100% 100% at bottom center);">
        <h2 class="text-gray-700 text-2xl font-semibold mb-4 mt-5">
          Start Roulette to<br>
          Discover Restaurant
        </h2>

        <p class="text-gray-600 mb-4 text-base">
          Once roulette stops, a random restaurant will be displayed for you.
        </p>

        <div class="flex justify-center">
          <button data-action="click->roulette#spin" id="start-roulette" class="bg-black text-white rounded-full py-3 px-8 font-medium hover:bg-gray-800 transition duration-300">
            Start Roulette
          </button>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<p>Find me in app/views/restaurants/new.html.erb</p>

app/views/restaurants/search.html.erb
<%= @restaurant.name %>

app/views/restaurants/show.html.erb
<div class="bg-white rounded-lg overflow-hidden">
  <div class="relative">
    <%= link_to restaurants_path, class: "absolute top-4 left-4 z-10 bg-white rounded-full p-2" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
      </svg>
    <% end %>

    <%= cl_image_tag @restaurant.photo.key, class: "w-full h-[200px] object-cover", width: 400, height: 400 %>
  </div>


  <div class="container mx-auto py-6 px-4">
    <h2 class="text-xl font-bold mb-2"><%= @restaurant.name %></h2>
    <div class="flex items-center gap-3 text-sm">
      <div class="flex items-center">
        <span>★</span>
        <span class="font-semibold ml-1"><%= @restaurant.rating %></span>
        <span class="ml-1">(<%= @restaurant.number_of_reviews %> reviews)</span>
      </div>
      <% if params[:address].present? %>
      <span>•</span>
        <% distance = Geocoder::Calculations.distance_between(params[:address], @restaurant.address, units: :km) %>
        <% walking_time = (distance * 1000 / 83.33).round %> <%# 83.33 m/min walking speed %>
        <span>≈ <%= walking_time %> min walk</span>
      <% end %>
    </div>
  </div>

  <div class="px-4 py-2">
    <div class="flex flex-wrap gap-2 mb-4">
      <% @restaurant.food_preferences.each do |preference| %>
        <span class="text-gray-600"><%= preference %></span>
        <% unless preference == @restaurant.food_preferences.last %>
          <span>•</span>
        <% end %>
      <% end %>
    </div>

    <div class="flex flex-wrap gap-2 mb-6">
      <% @restaurant.food_restrictions.each do |restriction| %>
        <span class="text-gray-600"><%= restriction %></span>
        <% unless restriction == @restaurant.food_restrictions.last %>
          <span>•</span>
        <% end %>
      <% end %>
    </div>

    <%= link_to new_restaurant_booking_path(@restaurant), class: "block w-full bg-black text-white text-center py-4 rounded-full font-medium text-lg" do %>
      Make Reservation
    <% end %>
  </div>
</div>

<div class="container mx-auto px-4 py-2">
  <div class="mt-8">
    <h3 class="text-lg font-semibold mb-4">Menu</h3>
    <div class="space-y-4">
      <% @restaurant.dishes.each do |dish| %>
        <div class="flex justify-between items-start">
          <div class="flex gap-4">
            <% if dish.photo.attached? %>
              <%= cl_image_tag dish.photo.key, class: "w-24 h-24 object-cover rounded-lg", width: 200, height: 200 %>
            <% end %>
            <div>
              <h4 class="font-medium"><%= dish.name %></h4>
              <p class="text-gray-600 text-sm"><%= dish.description %></p>
            </div>
          </div>
          <div class="text-right">
            <p class="font-medium">€<%= number_with_precision(dish.price, precision: 2) %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="mt-8">
    <h3 class="text-lg font-semibold mb-4">Other Restaurants You May Like</h3>
    <div class="space-y-4">
      <% @other_restaurants.each do |restaurant| %>
        <%= link_to restaurant_path(restaurant, food_preferences: params[:food_preferences], food_restrictions: params[:food_restrictions]) do %>
        <div class="flex justify-between items-start">
          <div class="flex gap-4">
            <% if restaurant.photo.attached? %>
              <%= cl_image_tag restaurant.photo.key, class: "w-24 h-24 object-cover rounded-lg", width: 200, height: 200 %>
            <% end %>
            <div>
              <h4 class="font-medium"><%= restaurant.name %></h4>
              <p class="text-gray-600 text-sm"><%= restaurant.address %></p>
              <div class="flex items-center gap-2 text-sm">
                <span class="text-gray-600">⭐ <%= restaurant.rating %></span>
                <span class="mx-2">•</span>
                <span class="text-gray-600"><%= restaurant.number_of_reviews %> reviews</span>
              </div>
            </div>
          </div>
        <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>