config/routes.rb
Rails.application.routes.draw do
  devise_for :restaurant_owners
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :users, only: [] do
    member do
      patch :restaurant_mode
      patch :experience_mode
    end
  end

  resources :bookings, only: [] do
    member do
      patch :accept
      patch :decline
    end
  end

  get "restaurant_search", to: "restaurants#search"

  resources :restaurants, only: [:index, :show, :new, :create, :edit, :update] do
    resources :bookings, only: [:new, :create]
  end

  get "experience_search", to: "experiences#search"

  resources :experiences, only: [:index, :show, :new, :create, :edit, :update] do
    resources :bookings, only: [:new, :create]
  end

  root "restaurants#index"

  get "/dashboard", to: "pages#dashboard"
  get "webmanifest"    => "pwa#manifest"
  get "service-worker" => "pwa#service_worker"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoiDe9</title>
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no">
    <meta name="mobile-web-app-capable" content="yes">
    <%= tag.link rel: "manifest", href: webmanifest_path(format: :json) %>
    <%= tag.link rel: "icon", href: image_url("app-icon-512.png"), type: "image/png" %>
    <%= tag.link rel: "apple-touch-icon", href: image_url("app-icon-512.png") %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="flex flex-col min-h-screen">
    <%= yield %>
  </body>
</html>